services:
  web:
    build: .
    container_name: findmyfaced_web

    # Use Gunicorn instead of runserver
    command: gunicorn --bind 0.0.0.0:8000 findmyfaced.wsgi:application
    ports:
      - "80:8000" # Map AWS traffic (port 80) to your container (8000)

    volumes:
      - ./app:/app
    env_file:
      - .env

    depends_on:
      - db

  db:
    image: pgvector/pgvector:pg16

    container_name: findmyfaced_db

    restart: always

    environment:
      POSTGRES_DB: findmyfaced
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: